# SPDX-FileCopyrightText: Noham Devillers <noham.devillers@enioka.com>
# SPDX-License-Identifier: GPL-2.0-or-later

START {
    recover cmd="ctl_cyrusdb -r -C /srv/cyrus/imapd.conf"
}

SERVICES {
    imap cmd="imapd -C /srv/cyrus/imapd.conf" listen="143" prefork=0
}

EVENTS {
    checkpoint cmd="ctl_cyrusdb -c -C /srv/cyrus/imapd.conf" period=30
}

