configdirectory: /srv/cyrus/conf
master_pid_file: /srv/cyrus/run/master.pid

defaultpartition: default
partition-default: /srv/cyrus/var/spool/mail
sievedir: /srv/cyrus/var/spool/sieve

cyrus_user: cyrus
cyrus_group: mail

allowplaintext: yes

sasl_pwcheck_method: alwaystrue
