# SPDX-FileCopyrightText: Noham Devillers <noham.devillers@enioka.com>
# SPDX-License-Identifier: GPL-2.0-or-later

dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.0

auth_allow_cleartext = yes
auth_mechanisms = plain login

listen = *
log_path = /dev/stdout
mail_driver = maildir
mail_path = /mail/%{user}
protocols = imap

passdb static {
  driver = static
  static_password = admin

  fields {
  }
}

userdb static {
  driver = static

  fields {
    gid = 1000
    home = /mail/%u
    uid = 1000
  }
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

protocol imap {
  mail_max_userip_connections = 1000
}
