listen = *
protocols = imap

disable_plaintext_auth = no
auth_mechanisms = plain login

mail_location = maildir:/mail/%u

passdb {
  driver = static
  args = password=admin
}

userdb {
  driver = static
  args = uid=1000 gid=1000 home=/mail/%u
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

protocol imap {
  mail_max_userip_connections = 1000 # Avoid too many connections for same user / ip
}

log_path = /dev/stdout
